name: flutter_login_ui
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_slider: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
   - assets/logos/facebook.jpg
   - assets/logos/google.jpg
   - assets/logos/logoWinABike.png
   - assets/logos/logo winabike web transparent TM.jpg
   - assets/logos/apple-id-black-yes_2x.png
   - assets/logos/og-default.jpg
   - assets/avatars/avatar_1.jpg
   - assets/logos/motorbike_text_final_201.png
   - assets/logos/line.png
   - assets/logos/line_in_less.png
   - assets/avatars/motorcycle.jpg
   - assets/avatars/bike.jpg
   - assets/avatars/motorbike.jpg
   - assets/avatars/smartphones_logo.png
   - assets/avatars/crashhelmet_logo.jpg
   - assets/avatars/motorbike_logos.png
   - assets/avatars/motorbike_logo.jpg
   - assets/avatars/watches_logo.jpg
   - assets/avatars/z_fold2_image.jpg
   - assets/avatars/apple_watch_image.jpg
   - assets/avatars/moto_helmet_image.jpg
   - assets/avatars/bike4.jpg
   - assets/avatars/bike3.jpg
   - assets/avatars/bike2.jpg
   - assets/avatars/bike1.jpg
   - assets/avatars/iphone11_pro_max.jpg
   - assets/avatars/note20.jpg
   - assets/avatars/mi10_ultra.jpg
   - assets/avatars/p40_pro.jpg
   - assets/avatars/z_flip.jpg
   - assets/avatars/pixel4.jpg


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf